In [3]:
#1. Create a 3x3 NumPy array with random integers between 1 and 100. Then, interchange its rows and columns
import numpy as np

# Generate a 3x3 array with random integers between 1 and 100 (inclusive)
arr = np.random.randint(1, 101, size=(3, 3))

# Interchange rows and columns using transposition
interchanged_arr = arr.T

# Print the original array and the interchanged array
print("Original array:\n", arr)
print("\nArray with rows and columns interchanged:\n", interchanged_arr)


Original array:
 [[27 30  1]
 [17 49 76]
 [60 82 12]]

Array with rows and columns interchanged:
 [[27 17 60]
 [30 49 82]
 [ 1 76 12]]


In [4]:
#2. Generate a 1D NumPy array with 10 elements. Reshape it into a 2x5 array, then into a 5x2 array.
import numpy as np

# Generate a 1D array with 10 elements
arr = np.arange(10)  # Creates an array from 0 to 9

# Reshape into a 2x5 array
reshaped_2x5 = arr.reshape(2, 5)

# Reshape into a 5x2 array
reshaped_5x2 = arr.reshape(5, 2)

# Print the original array and the reshaped arrays
print("Original array:", arr)
print("\nReshaped into 2x5 array:", reshaped_2x5)
print("\nReshaped into 5x2 array:", reshaped_5x2)


Original array: [0 1 2 3 4 5 6 7 8 9]

Reshaped into 2x5 array: [[0 1 2 3 4]
 [5 6 7 8 9]]

Reshaped into 5x2 array: [[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]


In [5]:
#3.Create a 4x4 NumPy array with random float values. Add a border of zeros around it, resulting in a 6x6 array.
import numpy as np

# Generate a 4x4 array with random float values
arr = np.random.rand(4, 4)

# Add a border of zeros using padding
padded_arr = np.pad(arr, pad_width=1, mode='constant', constant_values=0)

# Print the original array and the padded array
print("Original array:\n", arr)
print("\nArray with border of zeros:\n", padded_arr)


Original array:
 [[0.38346065 0.19876846 0.57310963 0.15295505]
 [0.99406465 0.56811981 0.24336346 0.10618796]
 [0.1391982  0.11134074 0.00576382 0.01847791]
 [0.51669124 0.47361307 0.32314791 0.03334469]]

Array with border of zeros:
 [[0.         0.         0.         0.         0.         0.        ]
 [0.         0.38346065 0.19876846 0.57310963 0.15295505 0.        ]
 [0.         0.99406465 0.56811981 0.24336346 0.10618796 0.        ]
 [0.         0.1391982  0.11134074 0.00576382 0.01847791 0.        ]
 [0.         0.51669124 0.47361307 0.32314791 0.03334469 0.        ]
 [0.         0.         0.         0.         0.         0.        ]]


In [6]:
#4. Using NumPy, create an array of integers from 10 to 60 with a step of 5.
import numpy as np

# Create the array using np.arange
arr = np.arange(10, 61, 5)

# Print the array
print(arr)


[10 15 20 25 30 35 40 45 50 55 60]


In [11]:
#5. Create a NumPy array of strings ['python', 'numpy', 'pandas']. Apply different case transformations
#(uppercase, lowercase, title case, etc.) to each element.
import numpy as np

# Create the array of strings
string_arr = np.array(['python', 'numpy', 'pandas'])

# Uppercase transformation (using np.char.upper)
uppercase_arr = np.char.upper(string_arr)

# Lowercase transformation
lowercase_arr = np.char.lower(string_arr)

# Title case transformation
title_arr = np.char.title(string_arr)

# Print the original array and transformed arrays
print("Original array:", string_arr)
print("\nUppercase:", uppercase_arr)
print("\nLowercase:", lowercase_arr)
print("\nTitle case:", title_arr)


Original array: ['python' 'numpy' 'pandas']

Uppercase: ['PYTHON' 'NUMPY' 'PANDAS']

Lowercase: ['python' 'numpy' 'pandas']

Title case: ['Python' 'Numpy' 'Pandas']


In [12]:
#6.Generate a NumPy array of words. Insert a space between each character of every word in the array.
import numpy as np

# Create a NumPy array of words
words = np.array(['hello', 'world', 'python'])

# Function to insert spaces between characters
def insert_spaces(word):
    return ' '.join(list(word))

# Apply the function to each element using vectorized operations
spaced_words = np.vectorize(insert_spaces)(words)

# Print the original and spaced arrays
print("Original array:", words)
print("\nArray with spaces between characters:", spaced_words)



Original array: ['hello' 'world' 'python']

Array with spaces between characters: ['h e l l o' 'w o r l d' 'p y t h o n']


In [14]:
#7. Create two 2D NumPy arrays and perform element-wise addition, subtraction, multiplication, and division.
import numpy as np

# Create two 2D NumPy arrays with random integers
arr1 = np.random.randint(1, 10, size=(3, 4))  # Creates a 3x4 array with random integers
arr2 = np.random.randint(1, 10, size=(3, 4))  # Creates another 3x4 array with random integers

# Element-wise addition
added_arr = arr1 + arr2

# Element-wise subtraction
subtracted_arr = arr1 - arr2

# Element-wise multiplication
multiplied_arr = arr1 * arr2

# Element-wise division (ensuring no division by zero)
divided_arr = np.divide(arr1, arr2, where=arr2 != 0)  # Avoids division by zero

# Print the original arrays and the results
print("Array 1:\n", arr1)
print("\nArray 2:\n", arr2)
print("\nAdded array:\n", added_arr)
print("\nSubtracted array:\n", subtracted_arr)
print("\nMultiplied array:\n", multiplied_arr)
print("\nDivided array:\n", divided_arr)


Array 1:
 [[3 5 4 5]
 [8 7 4 2]
 [2 8 4 5]]

Array 2:
 [[6 5 3 5]
 [9 9 4 4]
 [6 9 4 9]]

Added array:
 [[ 9 10  7 10]
 [17 16  8  6]
 [ 8 17  8 14]]

Subtracted array:
 [[-3  0  1  0]
 [-1 -2  0 -2]
 [-4 -1  0 -4]]

Multiplied array:
 [[18 25 12 25]
 [72 63 16  8]
 [12 72 16 45]]

Divided array:
 [[0.5        1.         1.33333333 1.        ]
 [0.88888889 0.77777778 1.         0.5       ]
 [0.33333333 0.88888889 1.         0.55555556]]


In [15]:
#8.Use NumPy to create a 5x5 identity matrix, then extract its diagonal elements.
import numpy as np

# Create a 5x5 identity matrix using np.eye
identity_matrix = np.eye(5)

# Extract diagonal elements using np.diagonal
diagonal_elements = np.diagonal(identity_matrix)

# Print the identity matrix and diagonal elements
print("Identity matrix:\n", identity_matrix)
print("\nDiagonal elements:", diagonal_elements)


Identity matrix:
 [[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]

Diagonal elements: [1. 1. 1. 1. 1.]


In [35]:
#9. Generate a NumPy array of 100 random integers between 0 and 1000. Find and display all prime numbers in
#this array.

import numpy as np

# Function to check if a number is prime
def is_prime(n):
    if n <= 1:
        return False
    if n <= 3:
        return True
    if n % 2 == 0 or n % 3 == 0:
        return False
    i = 5
    while i * i <= n:
        if n % i == 0 or n % (i + 2) == 0:
            return False
        i += 6
    return True

# Generate a NumPy array of 100 random integers between 0 and 1000
random_integers = np.random.randint(0, 1001, 100)

# Find all prime numbers in the array
primes_in_array = [num for num in random_integers if is_prime(num)]

print("Random integers:", random_integers)
print("Prime numbers in the array:", primes_in_array)



Random integers: [ 31  31 427 115 804 449 395 989 319  16 353 229 778 986 900 699 621 987
 800 649 125 595 779 767 516 163 523 891 864 984 356 845 959 479  48  55
 470 903 326 445 413 797 457 109  95 222 638 165 268 838 149  75 858 366
 765 457 848 498 590 186 508 716 974 882 897 897 192 694 845 969 831 792
 180 401 903  28 954 691 317 607 610 383 123 941 610 388 794 343 166 438
 862 241 420 250 164 955 600 603 398 910]
Prime numbers in the array: [31, 31, 449, 353, 229, 163, 523, 479, 797, 457, 109, 149, 457, 401, 691, 317, 607, 383, 941, 241]


In [36]:
#10. Create a NumPy array representing daily temperatures for a month. Calculate and display the weekly
#averages.
import numpy as np

# Generate a NumPy array representing daily temperatures for a month (30 days)
daily_temperatures = np.random.randint(20, 35, 30)  # Random temperatures between 20 and 35 degrees Celsius

# Calculate the weekly averages
weekly_averages = [np.mean(daily_temperatures[i:i+7]) for i in range(0, len(daily_temperatures), 7)]

print("Daily temperatures:", daily_temperatures)
print("Weekly averages:", weekly_averages)



Daily temperatures: [24 24 27 24 21 30 23 27 32 28 30 21 34 30 20 22 22 22 26 31 31 34 30 21
 28 20 21 23 24 22]
Weekly averages: [24.714285714285715, 28.857142857142858, 24.857142857142858, 25.285714285714285, 23.0]
